title: "uddin's Blog"
description: "uddin IT experience notes"
defaults:  
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
plugins:
    - jekyll-seo-tag
